config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'

  resources :items do
    resources :orders, only: [:index, :create]
  end

  post 'like/:item_id', to: 'likes#like', as: 'like'
  delete 'like/:item_id', to: 'likes#unlike', as: 'unlike'
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item, counter_cache: :likes_count
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_params

  def like
    like = current_user.likes.new(item_id: @item.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(item_id: @item.id)
    like.destroy
  end

  private
  def item_params
    require.permit
  end

  def set_params
    @item = Item.find(params[:item_id])
    @id_name = "#like-button-#{@item.id}"
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<%= link_to unlike_path(item.id), method: :delete, remote: true do %>
  <div class="star-icon">
    <%= icon "fa", "star", class: 'fa-lg' %>
  </div>
<% end %>
<span><%= item.likes.count %></span>

app/views/likes/_unlike.html.erb
<%= link_to like_path(item.id), method: :post, remote: true do %>
  <div class="star-icon">
    <%= icon "far", "star", class: 'fa-lg' %>
  </div>
<% end %>
<span><%= item.likes.count %></span>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/unlike", item: @item  )) %>');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", item: @item  )) %>');